Sander
MeesPos/web.kappers-project pull request #10
Opened 2022-12-10 15:30 UTC by sanderk12

2022-12-12 08:16 UTC, codingholt commented on components/Agenda.tsx
> +      <br />
Probeer het aantal linebreaks te verminderen, en de extra whitespace te maken met css _in tailwind_

2022-12-12 08:34 UTC, codingholt commented on components/Agenda.tsx
> +      <img className="ml-[40%]" src="fotos/Group5.png" width="80px" />
Voor dit soort dingen is geen afbeelding nodig, het is niet een goede kwaliteit als het een afbeelding is. Ook zorgt het voor langere laadtijden. Probeer ze na te maken in tailwind.

2022-12-12 08:34 UTC, codingholt commented on components/Agenda.tsx
> +        <br></br>
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 08:34 UTC, codingholt commented on components/Hoofdpagina.tsx
> +      <br />
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 08:35 UTC, codingholt commented on components/Hoofdpagina.tsx
> +      <br />
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 08:35 UTC, codingholt commented on components/Reservering2.tsx
> +      <br />
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 08:44 UTC, codingholt commented on pages/index.tsx
> +<<<<<<< Updated upstream
Zou je de volgende keer dit soort conflict kunnen oplossen voordat je een pull request opent? 
[Resolving Merge Conflicts](https://www.youtube.com/watch?v=JtIX3HJKwfo)

2022-12-12 08:47 UTC, codingholt commented on testfolder/kapperselecteren.html
> +                <br>
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 08:47 UTC, codingholt commented on testfolder/kapperselecteren.html
> +                <br>
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 08:48 UTC, codingholt commented on testfolder/kapperselecteren.html
> +            <div class="rechts">
in react gaat class niet werken, je zal className moeten gaan gebruiken

2022-12-12 09:17 UTC, codingholt commented on testfolder/mystyle.css
> +}
We hadden afgesproken om t in tailwind te doen :)
[YouTube video over tailwind](https://youtu.be/pfaSUYaSgRo) | [tailwind docs](https://tailwindcss.com/docs/width)

2022-12-12 09:18 UTC, codingholt commented on testfolder/reservering.html
> +                <br>
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 09:18 UTC, codingholt commented on testfolder/reservering.html
> +                <br>
Probeer dit soort linebreaks te vermijden. [Hiervoor is de linebreak tag niet bedoelt](https://stackoverflow.com/a/1726079/15682062). Als we het later responsive willen maken gaat dit niet met linebreaks. Proberer extra whitespace te maken met css in tailwind.

2022-12-12 09:20 UTC, codingholt commented on pages/mystyle.css
> +}
we hadden afgesproken om de css in tailwind te doen ;)

2022-12-12 09:21 UTC, codingholt commented on components/Hoofdpagina.tsx
> +      <img className="ml-[40%]" src="fotos/Group2.png" width="80px" />
Voor dit soort dingen is geen afbeelding nodig, het is niet een goede kwaliteit als het een afbeelding is. Ook zorgt het voor langere laadtijden. Probeer ze na te maken in tailwind.

2022-12-12 09:22 UTC, codingholt commented on styles/mystyle.css
> +}
We hadden afgesproken om de css in tailwind te doen ;)

2022-12-12 09:24 UTC, codingholt commented on testfolder/reservering.html
> +                <img src="fotos/Group1.png" width="80px"></img>
Voor dit soort dingen is geen afbeelding nodig, het is niet een goede kwaliteit als het een afbeelding is. Ook zorgt het voor langere laadtijden. Probeer ze na te maken in tailwind.

2022-12-19 09:06 UTC, MeesPos requested changes
Je hebt al heel wat dingen gefixed, maar er zijn nog wat dingen die nog gefixed moet worden.

Ook zie ik nog een testfolder met bestanden, lijkt me dat dit weg kan?

2022-12-20 08:48 UTC, MeesPos commented
Ik heb wat dingen nog gefixed, maar het is nog niet helemaal top. Ik merge hem nu wel, maar moeten nog wel wat dingen gefixed worden.

2022-12-20 08:48 UTC, merged